[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["John Doe <napat.asawa0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quixstreams = "^2.10.0"
websocket-client = "^1.8.0"
loguru = "^0.7.2"
python-dateutil = "^2.9.0.post0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
